#include "except.hpp"

int aborted = 0;


void run_abort(std::string cause){
    debug("Aborting!");

}
